### ISSUE TITLE
CallerID for calls made FROM internal caller shows outbound trunk CID

### ISSUE THREAD

**Issue by jacobdevans** [POSSA/freepbx-Call_Status#2]
Here's my situation,

OK: Calls FROM External to Internal = Call Time | outside_cid | inside_ext | SIP/inside_ext, SIP/PRI
OK: Calls from Internal to Internal = Call Time | inside_ext | inside_ext | SIP/Inside_ext, SIP/inside_ext
BAD: Calls from Internal to External = Call Time | trunk_cid | outside_cid | SIP/PRI, SIP/inside_ext

I would like trunk_cid to be the inside_ext, is this possible with regex or other manipulations? 

Thanks, this has worked great thus far.

**Comment by lgaetz** [comment]
Yes, but you have some work ahead of you. Most of data displayed for this simple web page is all parsed from the asterisk command `core show channels concise`. If you check out the file `status.php`, the array $pieces contains this information. The full channel name for each channel is $pieces[0], which can be used in the asterisk command `core show channel <full_channel_name>`, you can get a bunch more details including the extension number, name etc.

**Comment by lgaetz** [comment]
@jacobdevans I hit close issue by accident when I replied. Please don't take that as a sign that we are unwilling to discuss. Any issues, follow up here.

**Comment by JakeDEvans** [comment]
Thanks @lgaetz 
I'm considering an if statement, if [7] matches "ext number" display SIP/1XXX value, all my extensions are 4 digit, starting with a 1, I'd just need to figure out:
Regex match for 1000-1999
regex match for 8445551234 or 7175551234, exact matches.

should work fine, yes?
